### PR TITLE
Quickstart guide, keyframing, small updates

### PR DESCRIPTION
**Pull request by ifranda**
Adding two new notebooks

### CODE REVIEW

**Comment by ifranda** [comment]
Any suggestions are appreciated! 

For downloading the datasets and session files, I included links to the files in Google Drive. Let me know if there is a better way!

**Review by NihanthCW — CHANGES_REQUESTED** [review]
Thanks @ifranda. Looks good. A few suggestions:
- In the quickstart and other new notebooks. Can downloading the dataset be done as a cell int he notebook itself to prevent them from having to download it separately? What do you think?

**Comment by NihanthCW** [comment]
RDA would be a good option. I've moved [VAPOR sample data to RDA](https://rda.ucar.edu/datasets/ds897.7/dataaccess/). We can move Katrina data to the same place?

**Review by NihanthCW — COMMENTED** [review]
Awesome! Thanks Ian.
Two suggestions:
- The download is working great! It might be good to check if the file already exists so that people are not re-downloading the file every time they run the notebook. 
- How do you feel about including one cell to allow people rotate and look around in the scene just before exporting the image? Something similar to ``` viz = VaporVisualizerWidget(ses)```

**Comment by ifranda** [comment]
Good ideas! Another thought -- if users are following along by copying and pasting into their own workspace instead of cloning the whole repository, they won't have access to the get_data.py script. Another idea I had was to have a cell for command lines, like this:

```
!curl -o Katrina.zip "https://data.rda.ucar.edu/ds897.7/Katrina.zip"
!unzip -o Katrina.zip -d ./data
!rm Katrina.zip
```

**Comment by NihanthCW** [comment]
Agreed.

**Comment by ifranda** [comment]
Ok, I've made some updates and I think it runs better!

**Comment by ifranda** [comment]
I got the image renderer working with a fresh conda build! But it looks like Natural Earth is the only builtin map at the moment, and I think that one only renders land, unless I'm wrong about that? Do you know if there's a way to get the oceans to render? Otherwise maybe we could try adding BigBlueMarble to the builtin maps

This is what it looks like at the moment:
image

Using the filepath to BigBlueMarble:
image

**Comment by NihanthCW** [comment]
You are right. The oceans are black in the dataset. Could this be another file that we could download? Alternatively, the black ocean down't look bad too...
I believe we intentionally donot include blue marble to avoid making the maps package too large. 
Let's chat tomorrow.

**Review by NihanthCW — APPROVED** [review]

**Pull request merged**
